server:
  port: 8081
  servlet:
    context-path: /api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /swagger.v1+json
  api:
    title: Boot Ans Shoes
    description: Se proporciona un E-Commerce de zapatos
    version: 1.0

spring:
  application:
    name: ecommerce-boot-and-shoes-back
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-boot-and-shoes
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: debug
